### PR TITLE
WIP: removal of trailing whitespace

### PR DESCRIPTION
**Pull request by a1346054**
Split from #623 to allow for discussion on how to make sure trailing whitespace is removed and doesn't come back.

### CODE REVIEW

**Comment by Rondom** [comment]
I think, we can use wtf (whitespace total fixer) in CI for this simple task. https://github.com/dlenski/wtf

**Comment by Nikratio** [comment]
Are you still actively working on this?

**Comment by a1346054** [comment]
I'm still learning how other projects make sure no new trailing whitespace is introduced in git, without giving unhelpful error messages to the contributor or making it too cumbersome.

If anyone watching this wishes to provide some input, I'd appreciate it (or any help with it).

Feel free to leave this PR open, I will rebase the PR in case some conflicts are introduced.

**Comment by Nikratio** [comment]
Any update on this?

**Comment by Nikratio** [comment]
Will close this for now, feel free to re-open when this is ready for review.

**Pull request closed without merging**
