### PR TITLE
fuse_lowlevel: Remove useless NULL assert for se

### PR DESCRIPTION
**Pull request by winndows**
Remove useless NULL assert for se.

Signed-off-by: Liao Pingfang <liao.pingfang@zte.com.cn>

### CODE REVIEW

**Comment by Nikratio** [comment]
Could you explain why this is useless?

**Comment by winndows** [comment]
If it is useful, line 171: "if (se->debug) {" in this file will dereference NULL pointer.

**Comment by winndows** [comment]
> Could you explain why this is useless?

If it is useful, line 171: "if (se->debug) {" in this file will dereference NULL pointer.

**Comment by Nikratio** [comment]
That's actually a bug above, then. Probably the assert should go there, or the check for se->debug should first check for se !+= NULL.

**Comment by winndows** [comment]
> Could you explain why this is useless?

If it is useful, line 171: "if (se->debug) {" in this file will dereference NULL pointer.

**Pull request closed without merging**
