### PR TITLE
Optimize high level id/name hash efficiency

### PR DESCRIPTION
**Pull request by tianshan**
Signed-off-by: Tianshan Qu <qutianshan@gmail.com>

### CODE REVIEW

**Comment by Nikratio** [comment]
Why is this more efficient?

**Comment by tianshan** [comment]
@Nikratio bitwise AND is faster than mod operator

**Comment by trapexit** [comment]
Yes, but 1) have you ensured that the table is always a power of 2? 2) Unless the hash is called very often it won't really matter in practice on modern machines.

**Comment by tianshan** [comment]
@trapexit  
1) the initialize value is hard coded 8192 (NODE_TABLE_MIN_SIZE) assign in _node_table_init_,  table grow is always double in _node_table_resize_, table reduce is halved in _node_table_reduce_ 
2) id_hash and name_hash are called each request in lookup phase.
but indeed, the optimize is so little to observe in test

**Comment by jpandre** [comment]
Consider the code below :

unsigned int mod(unsigned int w)
{
        return (w % 8192);
}

gcc compiles it as :
        movl    %edi, %eax
        andl    $8191, %eax
        ret

So gcc does the optimization when relevant.

**Comment by tianshan** [comment]
@jpandre I think you are right, after enable compile optimization, the two ways are almost the same.
I will close this pr, thanks for yours time.

**Comment by Nikratio** [comment]
I'm not surprised that GCC optimizes division by a hardcoded value, but I doubt that it will do the same if the divisor is variable (as in the code). It's rather unlikely that static analysis can tell that `f->id_table.size` will always be a power of two, and checking this at runtime would incur an extra penalty.

The reason I haven't applied this yet is that I it makes the code *depend* on the table size being a power of two. This is currently true, but people may change it without realizing that this is a hidden requirement.

If someone wants to push this, then the best way forward would probably be to store just the exponent of the table size, which would make the requirement explicit.

**Pull request closed without merging**
