### PR TITLE
fuse-lowlevel: set pipe size to max

### PR DESCRIPTION
**Pull request by giuseppe**
on failure to set the pipe size, set it to the maximum allowed by the
kernel.

If the first request required more than the maximum allowed, the
can_grow flag would be reset thus preventing any further resize.

Grow the pipe to the maximum allowed to increase the likelihood of
using splice for successive requests instead of falling back to
read/write.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by Nikratio** [comment]
Thanks! Looking at this, wouldn't it be easier to get rid of the pipe growing logic and set it to the maximum size right from the beginning? Are there any disadvantages of having a large pipe size?

**Comment by giuseppe** [comment]
> Thanks! Looking at this, wouldn't it be easier to get rid of the pipe growing logic and set it to the maximum size right from the beginning? Are there any disadvantages of having a large pipe size?

I don't think there are disadvantages beside wasting some memory.  AFAICS the main advantage for the lazy allocation that is used now is that on a host with `/proc/sys/fs/pipe-max-size` set to a big value, we will always use the biggest value even in the case there won't be any request that needs it.
With the current code instead we are sure we set the maximum value only if there was already a request that needed more than the maximum size.

**Comment by giuseppe** [comment]
@Nikratio anything more to move this PR forward?

**Comment by Nikratio** [comment]
Sorry for the delay. I suspect that just requesting a large size will not consume any memory unless someone actually writes that much data, and that it would therefore be okay to simplify the code. However, I don't have time to confirm so will do the conservative choice and merge as-is. Thanks!

**Comment by bsbernd** [comment]
@yangyun50 Sorry had missed your question, yes this patch is wrong, kernel `fuse_dev_do_read` checks the max buffer size and if not provided it fails

`fuse_dev_do_read
```
	if (nbytes < max_t(size_t, FUSE_MIN_READ_BUFFER,
			   sizeof(struct fuse_in_header) +
			   sizeof(struct fuse_write_in) +
			   fc->max_write))
		return -EINVAL;
```

**Comment by bsbernd** [comment]
https://github.com/libfuse/libfuse/pull/1465

**Pull request merged**
