### PR TITLE
Fix gcc warnings

### PR DESCRIPTION
**Pull request by forgottenswitch**
Stub compile warnings. Maybe some should be error-checked.

### CODE REVIEW

**Comment by Nikratio** [comment]
Hmm. I think gcc warning about `(void) chdir("/");` is a bug in GCC. The explicit cast makes it clear that we are deliberately ignoring the return value. In my opinion the empty `if` clauses introduced by your patch are worse than the GCC warning, so I'd rather add some more explicit `(void)` castings instead and hope that gcc gets fixed.

**Comment by forgottenswitch** [comment]
Then it's a bug in LLVM/clang too.
  #define IGNORE_RESULT(op) if ((op)) { }
?

**Comment by Nikratio** [comment]
Amazing that there's actually a discussion about this. I didn't read the bug to the end (so I don't know which opinion eventually prevailed), but the only thing that's going to get into FUSE is a void cast and (if necessary) a patch to enable `-Wno-unused-result` when compiling with gcc6 (in gcc 4.9 the behavior is still - dare I say it? - sensible).

**Comment by Nikratio** [comment]
Not interested in at least adding the `(void)` castings? I can easily to it, but then you won't be the commit author (and you found the problem).

**Pull request closed without merging**
