### PR TITLE
Add support for FOPEN_NOFLUSH flag

### PR DESCRIPTION
**Pull request by amir73il**
The support for the flag was added by commit a390ccb316be ("fuse: add FOPEN_NOFLUSH") to kernel v5.16-rc1

### CODE REVIEW

**Comment by Nikratio** [comment]
Thanks, looks good! Please just document the new flag in ChangeLog.rst.

**Comment by Nikratio** [comment]
This seems to break a unit test...?

**Comment by amir73il** [comment]
Interesting.
The test was not supposed to change logically for writeback=True, but there are those mutex locks that may have changed timing. I will remove them from the writeback=True case.

However, the assertion that failed (ERROR: Expected 8192 bytes, got 4096) is not really guaranteed with writeback cache enabled - it is only very probable...

**Comment by Nikratio** [comment]
The idea with the assertion is probably to test that writes are indeed cached without relying on timing. So maybe it is sufficient to reduce the size of userspace writes and/or change the assertion to not-equal to userspace write size...

**Comment by aakefbs** [comment]
It is there a reason this is not merged yet?

**Comment by aakefbs** [comment]
Thanks for merging @Nikratio !

**Pull request merged**
