### PR TITLE
Ask pkgconfig where we should install udev rules

### PR DESCRIPTION
**Pull request by heirecka**

### CODE REVIEW

**Comment by Nikratio** [comment]
Why do you think this is better? On Debian, *libdir* is `usr/lib`, but udev rules are supposed to go in `/lib/`.

**Comment by heirecka** [comment]
All those small differences between distros ;-)

Guess I could ask udev about udevdir via pkg-config to make everybody happy.

**Comment by Nikratio** [comment]
Is there a way to use pkg-config? That would be great.

**Comment by Nikratio** [comment]
Thanks!

**Pull request merged**
