### PR TITLE
Add a github actions file

### PR DESCRIPTION
**Pull request by bsbernd**
converted from travis with _sligh_ editing by
https://akx.github.io/travis-to-github-actions/

### CODE REVIEW

**Comment by bsbernd** [comment]
@Nikratio No idea if this works, maybe we can give it a try?

**Comment by bsbernd** [comment]
I just got a mail from git telling me that the automatic build failed - so this basically works, but has issues.

**Comment by Nikratio** [comment]
I don't see any output anywhere (I would have expected something under the "Checks" tab). But maybe it need to be merged first, let's try.

**Comment by bsbernd** [comment]
@Nikratio I got emails from github that my patch had failed, because of the missing cpp -DHAVE_PRIVATE....

Not sure if you get full logs:
https://github.com/bsbernd/libfuse/actions/runs/4213988753/jobs/7314133328

**Comment by bsbernd** [comment]
I think we should try out a test patch, but I'm rather busy today and traveling tomorrow.

**Comment by Nikratio** [comment]
Thanks for your help on this! At least following a merge, the test scripts are being run now. They currently fail because what looks like a toolchain incompatibility with me (valgrind not liking the clang debug information). I'll look into this.

**Pull request merged**
