### PR TITLE
Add an option to disable building tests

### PR DESCRIPTION
**Pull request by asafkahlon**
Signed-off-by: Asaf Kahlon <asafka7@gmail.com>

### CODE REVIEW

**Comment by Nikratio** [comment]
Thanks for the patch! Can you explain the use-case in which not compiling (and thus running) the tests is desirable?

**Comment by asafkahlon** [comment]
The case is not compiling and not running the tests, which is currently not possible when just invoking a regular build with `meson`.

If, for example, you compile an embedded linux system and you want to include `libfuse` in it, you don't want to compile the tests because they won't be installed on the target board.

**Comment by Nikratio** [comment]
Not sure I follow. Tests will never be installed, no matter if embedded or not. They should still be run before installation though, to ensure that everything works.

**Comment by asafkahlon** [comment]
@Nikratio Yeah, I know the tests won't be installed, but why would you want to compile them over and over again unless explicitly asked?
Anyway, you need to explicitly run another command in order to run the tests, so I don't think we should compile them if we don't have an intention to actually run them too.

**Pull request merged**
