### PR TITLE
Version symbol

### PR DESCRIPTION
**Pull request by aakefbs**
This branch is supposed to fix handling with libcs that do not provide versioned symbols.

### CODE REVIEW

**Comment by aakefbs** [comment]
Hmm, somehow the tests do not run?

**Comment by giuliobenetti** [comment]
@aakefbs it built successfully with all the combinations uclibc included in all the possible versions we have in Buildroot and old external toolchain! Thanks a lot! I think you can merge it now.

**Comment by Nikratio** [comment]
That's probably because the Travis-CI open-source credits have run out again. I'll email them. Sadly this seems to be the only way to get them refilled.

If anyone knows a less bureaucratic CI for open-source projects, please let me know.

**Comment by giuliobenetti** [comment]
@Nikratio would it be possible to release version 3.12.1 at this point?

**Comment by aakefbs** [comment]
github has its own internal test frame work, we could try to use that.

**Comment by Nikratio** [comment]
Could you try to push this again? In https://github.com/libfuse/libfuse/pull/720 the tests are now working.

**Comment by aakefbs** [comment]
Thanks Nikolaus, just closed and re-opened the pull request to trigger the tests - seems to work now.

**Review by pzhlkj6612 — CHANGES_REQUESTED** [review]
Hello! We seem to be missing a square bracket.

**Comment by aakefbs** [comment]
Thanks @pzhlkj6612 . Fixed

**Comment by Nikratio** [comment]
Thank you for this diligent patch. This makes things cleaner and easier to understand. I'm happy to merge this, but can you please fix the minor bug that you introduced in the test script? It currently causes tests to fail because you are attempting to create the same directory twice.

**Comment by aakefbs** [comment]
Sorry @Nikratio,  I had tested all, except of the script changes.

**Pull request merged**
