### PR TITLE
Naive attempt at handling nofail

### PR DESCRIPTION
**Pull request by jsoref**
issue #211 

I have no idea if this will work. But is this the right file/direction?

### CODE REVIEW

**Comment by Nikratio** [comment]
That really depends on what you are trying to achieve. Maybe you could elaborate on your goals?

**Comment by Nikratio** [comment]
Sorry, just saw the issue reference. No, this is the wrong way to do it. As the issue says, this needs to be filtered out in the mount helper.

**Comment by jsoref** [comment]
@Nikratio: where is that?

**Comment by Nikratio** [comment]
https://github.com/libfuse/libfuse/blob/master/util/mount.fuse.c#L155

**Comment by jsoref** [comment]
@nikratio: how's this?

**Comment by Nikratio** [comment]
Doesn't look right to me. Why do you think the presence of `nofail` should affect the exit code?

**Comment by jsoref** [comment]
Sorry. The documentation for this stuff is more or less vaporous. `nofail` definitely affects *someone*'s handling of an error status. But, I think you're right, it's just the caller's understanding of the error status, not the callee.

I'll try to post the obvious/simpler fix (closer to my original, but for this file) tonight.

**Comment by jsoref** [comment]
@Nikratio : how about this? :)

**Comment by jsoref** [comment]
@Nikratio : done

**Comment by ShapeShifter499** [comment]
Is this fix good for all of fuse or do I have to contact the dev behind megerfs as well?

@trapexit Pinging you here since I see this trying to use mergerfs in fstab with the 'nofail' option

**Pull request merged**
