### PR TITLE
Order locks in get_path2 to avoid deadlocks

### PR DESCRIPTION
**Pull request by billziss-gh**
This PR should fix issue #245. The same patch fixes a similar problem in OSXFUSE; see osxfuse/osxfuse#495

The PR passes all tests performed by `sudo python3 -m pytest test/`. I have not performed any additional testing at this time.

### CODE REVIEW

**Comment by bnaylor** [comment]
Do not consider this a barrier to acceptance by any means, but I will also test this patch tomorrow with our internal tests that also uncovered this issue.  Will update with results.

**Comment by billziss-gh** [comment]
@bnaylor absolutely. Looking forward to hear about the results.

**Comment by bnaylor** [comment]
I still experience hangs with this change, but as we may be discovering in the issue page, my problem may be something specific to the bsd fuse kernel module.

**Comment by billziss-gh** [comment]
I am withdrawing this patch as I have also discovered cases that it does not handle. My apologies for the noise. More information on the issue page.

**Pull request closed without merging**
