### PR TITLE
notify_store_retrieve.c: Fix the races

### PR DESCRIPTION
**Pull request by bsbernd**
Fix races and ignore errors.

### CODE REVIEW

**Comment by Nikratio** [comment]
Is this intended for merging, or just for temporary debugging on the CI?

**Comment by bsbernd** [comment]
Both, so far looks like we will need to accept ENOENT. I still get it at umount. Please don't merge yet, but I also need github runs - cannot convert it to draft (if I'm not mistaken, draft avoids github runs).

**Comment by bsbernd** [comment]
@Nikratio I have added the explanation in the commit message and a bit into the code. Commenting out the sleep line I now get at umount time

```
bschubert2@imesrv6 build-ubuntu>example/notify_store_retrieve -f --update-interval=1  /tmp/test
ERROR: fuse_lowlevel_notify_store() failed with No such file or directory (2) is_umount 0 open_cnt 5 lookup_cnt 1
ERROR: fuse_lowlevel_notify_store() failed with No such file or directory (2) is_umount 0 open_cnt 5 lookup_cnt 1
ERROR: fuse_lowlevel_notify_store() failed with No such file or directory (2) is_umount 0 open_cnt 5 lookup_cnt 1
ERROR: fuse_lowlevel_notify_store() failed with No such file or directory (2) is_umount 0 open_cnt 5 lookup_cnt 1
ERROR: fuse_lowlevel_notify_store() failed with No such file or directory (2) is_umount 0 open_cnt 5 lookup_cnt 1
ERROR: fuse_lowlevel_notify_store() failed with No such file or directory (2) is_umount 0 open_cnt 5 lookup_cnt 1
ERROR: fuse_lowlevel_notify_store() failed with No such file or directory (2) is_umount 0 open_cnt 5 lookup_cnt 1
ERROR: fuse_lowlevel_notify_store() failed with No such file or directory (2) is_umount 0 open_cnt 5 lookup_cnt 1
ERROR: fuse_lowlevel_notify_store() failed with No such file or directory (2) is_umount 0 open_cnt 5 lookup_cnt 1
ERROR: fuse_lowlevel_notify_store() failed with No such file or directory (2) is_umount 0 open_cnt 5 lookup_cnt 1
ERROR: fuse_lowlevel_notify_store() failed with No such file or directory (2) is_umount 0 open_cnt 5 lookup_cnt 1
fuse: writing device: Bad file descriptor
bschubert2@imesrv6 build-ubuntu>echo $?
0
```

**Comment by bsbernd** [comment]
I'm merging this without review to reduce the number of test failures. Feel free to send reviews post merge, I'm going to address these.

**Pull request merged**
